-- Afrigoals initial schema baseline.
--
-- Generated with pg_dump from the schema GORM's AutoMigrate produces, so it
-- matches what the Go models expect rather than a hand-written approximation.
-- Do not edit this file: add a new migration instead.

--
--

--
-- Name: analysis_event_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_event_stats (
    id bigint NOT NULL,
    uuid uuid DEFAULT gen_random_uuid(),
    analysis_event_id bigint NOT NULL,
    player_id bigint,
    player_name character varying(255),
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    distance_covered_m numeric(10,2),
    average_speed_kmh numeric(10,2),
    max_speed_kmh numeric(10,2),
    sprints_count bigint,
    touches_count bigint,
    source character varying(100) DEFAULT 'ai_model'::character varying,
    model_version character varying(50),
    job_id character varying(255),
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: analysis_event_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.analysis_event_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: analysis_event_stats_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.analysis_event_stats_id_seq OWNED BY public.analysis_event_stats.id;

--
-- Name: analysis_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_events (
    id bigint NOT NULL,
    uuid uuid DEFAULT gen_random_uuid(),
    match_id bigint NOT NULL,
    video_id bigint,
    type character varying(50) NOT NULL,
    timestamp_seconds numeric NOT NULL,
    player_id bigint,
    player_name character varying(255),
    notes text,
    clip_url character varying(500),
    stats_id bigint,
    created_by bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: analysis_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.analysis_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: analysis_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.analysis_events_id_seq OWNED BY public.analysis_events.id;

--
-- Name: article_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_tags (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    article_id bigint,
    tag text
);

--
-- Name: article_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.article_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: article_tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.article_tags_id_seq OWNED BY public.article_tags.id;

--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    author_id bigint,
    author_name text,
    title text,
    slug text,
    content text,
    excerpt text,
    featured_image text,
    category text,
    published boolean,
    published_at timestamp with time zone,
    read_time text
);

--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: articles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.articles_id_seq OWNED BY public.articles.id;

--
-- Name: clips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clips (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    match_id bigint NOT NULL,
    video_id bigint,
    event_id bigint,
    title character varying(200) NOT NULL,
    start_sec bigint NOT NULL,
    end_sec bigint,
    clip_url character varying(500),
    tags character varying(500),
    created_by bigint NOT NULL
);

--
-- Name: clips_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: clips_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clips_id_seq OWNED BY public.clips.id;

--
-- Name: club_leagues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.club_leagues (
    club_id bigint NOT NULL,
    league_id bigint NOT NULL
);

--
-- Name: clubs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clubs (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    name text NOT NULL
);

--
-- Name: clubs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clubs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: clubs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clubs_id_seq OWNED BY public.clubs.id;

--
-- Name: formations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.formations (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    match_id bigint,
    club_id bigint,
    formation text
);

--
-- Name: formations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.formations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: formations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.formations_id_seq OWNED BY public.formations.id;

--
-- Name: leagues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leagues (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid NOT NULL,
    name text NOT NULL,
    country text,
    description text
);

--
-- Name: leagues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.leagues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: leagues_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.leagues_id_seq OWNED BY public.leagues.id;

--
-- Name: lineup_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lineup_players (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    formation_id bigint,
    player_id bigint,
    name text,
    jersey_number bigint,
    "position" text,
    x numeric,
    y numeric
);

--
-- Name: lineup_players_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.lineup_players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: lineup_players_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.lineup_players_id_seq OWNED BY public.lineup_players.id;

--
-- Name: match_analysts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_analysts (
    match_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: match_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_events (
    id bigint NOT NULL,
    uuid uuid DEFAULT gen_random_uuid(),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    match_id bigint NOT NULL,
    team character varying(50),
    player character varying(120),
    jersey_number bigint,
    type character varying(50) NOT NULL,
    minute bigint NOT NULL,
    description character varying(500)
);

--
-- Name: match_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.match_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: match_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.match_events_id_seq OWNED BY public.match_events.id;

--
-- Name: match_videos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_videos (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    match_id bigint,
    original_filename text,
    video_url text
);

--
-- Name: match_videos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.match_videos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: match_videos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.match_videos_id_seq OWNED BY public.match_videos.id;

--
-- Name: matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matches (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    home_club_id bigint,
    away_club_id bigint,
    league_id bigint,
    date timestamp with time zone,
    score_home bigint,
    score_away bigint
);

--
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: matches_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.matches_id_seq OWNED BY public.matches.id;

--
-- Name: player_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_stats (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    player_id bigint,
    goals bigint,
    assists bigint,
    matches bigint,
    minutes bigint,
    yellow_cards bigint,
    red_cards bigint,
    shots bigint,
    on_target bigint,
    passes bigint,
    tackles bigint,
    saves bigint,
    clean_sheets bigint
);

--
-- Name: player_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.player_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: player_stats_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.player_stats_id_seq OWNED BY public.player_stats.id;

--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    club_id bigint,
    name text,
    jersey_number bigint,
    "position" text,
    photo_url text,
    date_of_birth timestamp with time zone,
    nationality text
);

--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: players_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.players_id_seq OWNED BY public.players.id;

--
-- Name: substitutes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.substitutes (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    formation_id bigint,
    player_id bigint,
    name text,
    jersey_number bigint,
    "position" text
);

--
-- Name: substitutes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.substitutes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: substitutes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.substitutes_id_seq OWNED BY public.substitutes.id;

--
-- Name: unavailable_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unavailable_players (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    uuid uuid,
    formation_id bigint,
    player_id bigint,
    name text,
    jersey_number bigint,
    "position" text,
    reason text,
    details text
);

--
-- Name: unavailable_players_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.unavailable_players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: unavailable_players_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.unavailable_players_id_seq OWNED BY public.unavailable_players.id;

--
-- Name: upload_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upload_sessions (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    match_id bigint NOT NULL,
    created_by bigint NOT NULL,
    filename character varying(255) NOT NULL,
    total_size bigint NOT NULL,
    chunk_size bigint NOT NULL,
    total_chunks bigint NOT NULL,
    status character varying(30) DEFAULT 'uploading'::character varying NOT NULL,
    final_path character varying(500),
    error_msg character varying(500)
);

--
-- Name: upload_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.upload_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: upload_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.upload_sessions_id_seq OWNED BY public.upload_sessions.id;

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    role character varying(50) NOT NULL,
    club_id bigint,
    league_id bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

--
-- Name: video_analysis_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.video_analysis_jobs (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    requested_by_user_id bigint,
    job_id character varying(128) NOT NULL,
    status character varying(32) DEFAULT 'queued'::character varying NOT NULL,
    original_filename character varying(255),
    model_message text,
    stage character varying(128),
    progress numeric,
    result_json text,
    annotated_video_path text,
    siglip_html_path text,
    video_id bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: video_analysis_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.video_analysis_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: video_analysis_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.video_analysis_jobs_id_seq OWNED BY public.video_analysis_jobs.id;

--
-- Name: videos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.videos (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    match_id bigint NOT NULL,
    league_id bigint,
    club_id bigint,
    title character varying(200) NOT NULL,
    provider character varying(50) DEFAULT 'upload'::character varying NOT NULL,
    url character varying(500) NOT NULL,
    thumbnail_url character varying(500),
    duration_sec bigint,
    original_filename character varying(255),
    video_url character varying(500),
    created_by bigint NOT NULL
);

--
-- Name: videos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.videos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: videos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.videos_id_seq OWNED BY public.videos.id;

--
-- Name: analysis_event_stats id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_event_stats ALTER COLUMN id SET DEFAULT nextval('public.analysis_event_stats_id_seq'::regclass);

--
-- Name: analysis_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_events ALTER COLUMN id SET DEFAULT nextval('public.analysis_events_id_seq'::regclass);

--
-- Name: article_tags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tags ALTER COLUMN id SET DEFAULT nextval('public.article_tags_id_seq'::regclass);

--
-- Name: articles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles ALTER COLUMN id SET DEFAULT nextval('public.articles_id_seq'::regclass);

--
-- Name: clips id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clips ALTER COLUMN id SET DEFAULT nextval('public.clips_id_seq'::regclass);

--
-- Name: clubs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs ALTER COLUMN id SET DEFAULT nextval('public.clubs_id_seq'::regclass);

--
-- Name: formations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formations ALTER COLUMN id SET DEFAULT nextval('public.formations_id_seq'::regclass);

--
-- Name: leagues id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leagues ALTER COLUMN id SET DEFAULT nextval('public.leagues_id_seq'::regclass);

--
-- Name: lineup_players id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lineup_players ALTER COLUMN id SET DEFAULT nextval('public.lineup_players_id_seq'::regclass);

--
-- Name: match_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_events ALTER COLUMN id SET DEFAULT nextval('public.match_events_id_seq'::regclass);

--
-- Name: match_videos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_videos ALTER COLUMN id SET DEFAULT nextval('public.match_videos_id_seq'::regclass);

--
-- Name: matches id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches ALTER COLUMN id SET DEFAULT nextval('public.matches_id_seq'::regclass);

--
-- Name: player_stats id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_stats ALTER COLUMN id SET DEFAULT nextval('public.player_stats_id_seq'::regclass);

--
-- Name: players id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players ALTER COLUMN id SET DEFAULT nextval('public.players_id_seq'::regclass);

--
-- Name: substitutes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.substitutes ALTER COLUMN id SET DEFAULT nextval('public.substitutes_id_seq'::regclass);

--
-- Name: unavailable_players id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unavailable_players ALTER COLUMN id SET DEFAULT nextval('public.unavailable_players_id_seq'::regclass);

--
-- Name: upload_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_sessions ALTER COLUMN id SET DEFAULT nextval('public.upload_sessions_id_seq'::regclass);

--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

--
-- Name: video_analysis_jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.video_analysis_jobs ALTER COLUMN id SET DEFAULT nextval('public.video_analysis_jobs_id_seq'::regclass);

--
-- Name: videos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos ALTER COLUMN id SET DEFAULT nextval('public.videos_id_seq'::regclass);

--
-- Name: analysis_event_stats analysis_event_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_event_stats
    ADD CONSTRAINT analysis_event_stats_pkey PRIMARY KEY (id);

--
-- Name: analysis_events analysis_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_events
    ADD CONSTRAINT analysis_events_pkey PRIMARY KEY (id);

--
-- Name: article_tags article_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tags
    ADD CONSTRAINT article_tags_pkey PRIMARY KEY (id);

--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);

--
-- Name: clips clips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clips
    ADD CONSTRAINT clips_pkey PRIMARY KEY (id);

--
-- Name: club_leagues club_leagues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_leagues
    ADD CONSTRAINT club_leagues_pkey PRIMARY KEY (club_id, league_id);

--
-- Name: clubs clubs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_pkey PRIMARY KEY (id);

--
-- Name: formations formations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formations
    ADD CONSTRAINT formations_pkey PRIMARY KEY (id);

--
-- Name: leagues leagues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leagues
    ADD CONSTRAINT leagues_pkey PRIMARY KEY (id);

--
-- Name: lineup_players lineup_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lineup_players
    ADD CONSTRAINT lineup_players_pkey PRIMARY KEY (id);

--
-- Name: match_analysts match_analysts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_analysts
    ADD CONSTRAINT match_analysts_pkey PRIMARY KEY (match_id, user_id);

--
-- Name: match_events match_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_events
    ADD CONSTRAINT match_events_pkey PRIMARY KEY (id);

--
-- Name: match_videos match_videos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_videos
    ADD CONSTRAINT match_videos_pkey PRIMARY KEY (id);

--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);

--
-- Name: player_stats player_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_stats
    ADD CONSTRAINT player_stats_pkey PRIMARY KEY (id);

--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);

--
-- Name: substitutes substitutes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.substitutes
    ADD CONSTRAINT substitutes_pkey PRIMARY KEY (id);

--
-- Name: unavailable_players unavailable_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unavailable_players
    ADD CONSTRAINT unavailable_players_pkey PRIMARY KEY (id);

--
-- Name: users uni_users_uuid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uni_users_uuid UNIQUE (uuid);

--
-- Name: upload_sessions upload_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_sessions
    ADD CONSTRAINT upload_sessions_pkey PRIMARY KEY (id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: video_analysis_jobs video_analysis_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.video_analysis_jobs
    ADD CONSTRAINT video_analysis_jobs_pkey PRIMARY KEY (id);

--
-- Name: videos videos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (id);

--
-- Name: idx_analysis_event_stats_analysis_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_event_stats_analysis_event_id ON public.analysis_event_stats USING btree (analysis_event_id);

--
-- Name: idx_analysis_event_stats_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_event_stats_job_id ON public.analysis_event_stats USING btree (job_id);

--
-- Name: idx_analysis_event_stats_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_analysis_event_stats_uuid ON public.analysis_event_stats USING btree (uuid);

--
-- Name: idx_analysis_events_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_events_created_by ON public.analysis_events USING btree (created_by);

--
-- Name: idx_analysis_events_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_events_match_id ON public.analysis_events USING btree (match_id);

--
-- Name: idx_analysis_events_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_events_player_id ON public.analysis_events USING btree (player_id);

--
-- Name: idx_analysis_events_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_events_type ON public.analysis_events USING btree (type);

--
-- Name: idx_analysis_events_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_analysis_events_uuid ON public.analysis_events USING btree (uuid);

--
-- Name: idx_analysis_events_video_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_events_video_id ON public.analysis_events USING btree (video_id);

--
-- Name: idx_article_tags_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_tags_deleted_at ON public.article_tags USING btree (deleted_at);

--
-- Name: idx_article_tags_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_article_tags_uuid ON public.article_tags USING btree (uuid);

--
-- Name: idx_articles_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_articles_deleted_at ON public.articles USING btree (deleted_at);

--
-- Name: idx_articles_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_articles_slug ON public.articles USING btree (slug);

--
-- Name: idx_articles_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_articles_uuid ON public.articles USING btree (uuid);

--
-- Name: idx_clips_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clips_created_by ON public.clips USING btree (created_by);

--
-- Name: idx_clips_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clips_event_id ON public.clips USING btree (event_id);

--
-- Name: idx_clips_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clips_match_id ON public.clips USING btree (match_id);

--
-- Name: idx_clips_video_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clips_video_id ON public.clips USING btree (video_id);

--
-- Name: idx_clubs_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clubs_deleted_at ON public.clubs USING btree (deleted_at);

--
-- Name: idx_clubs_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_clubs_uuid ON public.clubs USING btree (uuid);

--
-- Name: idx_formations_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_formations_deleted_at ON public.formations USING btree (deleted_at);

--
-- Name: idx_formations_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_formations_uuid ON public.formations USING btree (uuid);

--
-- Name: idx_leagues_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_leagues_deleted_at ON public.leagues USING btree (deleted_at);

--
-- Name: idx_leagues_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_leagues_uuid ON public.leagues USING btree (uuid);

--
-- Name: idx_lineup_players_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lineup_players_deleted_at ON public.lineup_players USING btree (deleted_at);

--
-- Name: idx_lineup_players_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_lineup_players_uuid ON public.lineup_players USING btree (uuid);

--
-- Name: idx_match_events_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_match_events_match_id ON public.match_events USING btree (match_id);

--
-- Name: idx_match_events_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_match_events_team ON public.match_events USING btree (team);

--
-- Name: idx_match_events_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_match_events_type ON public.match_events USING btree (type);

--
-- Name: idx_match_events_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_match_events_uuid ON public.match_events USING btree (uuid);

--
-- Name: idx_match_videos_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_match_videos_deleted_at ON public.match_videos USING btree (deleted_at);

--
-- Name: idx_match_videos_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_match_videos_match_id ON public.match_videos USING btree (match_id);

--
-- Name: idx_match_videos_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_match_videos_uuid ON public.match_videos USING btree (uuid);

--
-- Name: idx_matches_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_matches_deleted_at ON public.matches USING btree (deleted_at);

--
-- Name: idx_matches_league_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_matches_league_id ON public.matches USING btree (league_id);

--
-- Name: idx_matches_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_matches_uuid ON public.matches USING btree (uuid);

--
-- Name: idx_player_stats_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_stats_deleted_at ON public.player_stats USING btree (deleted_at);

--
-- Name: idx_player_stats_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_player_stats_uuid ON public.player_stats USING btree (uuid);

--
-- Name: idx_players_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_players_deleted_at ON public.players USING btree (deleted_at);

--
-- Name: idx_players_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_players_uuid ON public.players USING btree (uuid);

--
-- Name: idx_substitutes_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_substitutes_deleted_at ON public.substitutes USING btree (deleted_at);

--
-- Name: idx_substitutes_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_substitutes_uuid ON public.substitutes USING btree (uuid);

--
-- Name: idx_unavailable_players_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_unavailable_players_deleted_at ON public.unavailable_players USING btree (deleted_at);

--
-- Name: idx_unavailable_players_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_unavailable_players_uuid ON public.unavailable_players USING btree (uuid);

--
-- Name: idx_upload_sessions_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_sessions_created_by ON public.upload_sessions USING btree (created_by);

--
-- Name: idx_upload_sessions_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_sessions_match_id ON public.upload_sessions USING btree (match_id);

--
-- Name: idx_upload_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_upload_sessions_status ON public.upload_sessions USING btree (status);

--
-- Name: idx_users_club_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_club_id ON public.users USING btree (club_id);

--
-- Name: idx_users_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);

--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);

--
-- Name: idx_users_league_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_league_id ON public.users USING btree (league_id);

--
-- Name: idx_video_analysis_jobs_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_video_analysis_jobs_job_id ON public.video_analysis_jobs USING btree (job_id);

--
-- Name: idx_video_analysis_jobs_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_video_analysis_jobs_match_id ON public.video_analysis_jobs USING btree (match_id);

--
-- Name: idx_video_analysis_jobs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_video_analysis_jobs_status ON public.video_analysis_jobs USING btree (status);

--
-- Name: idx_video_analysis_jobs_video_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_video_analysis_jobs_video_id ON public.video_analysis_jobs USING btree (video_id);

--
-- Name: idx_videos_club_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_videos_club_id ON public.videos USING btree (club_id);

--
-- Name: idx_videos_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_videos_created_by ON public.videos USING btree (created_by);

--
-- Name: idx_videos_league_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_videos_league_id ON public.videos USING btree (league_id);

--
-- Name: idx_videos_match_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_videos_match_id ON public.videos USING btree (match_id);

--
-- Name: analysis_event_stats fk_analysis_event_stats_analysis_event; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_event_stats
    ADD CONSTRAINT fk_analysis_event_stats_analysis_event FOREIGN KEY (analysis_event_id) REFERENCES public.analysis_events(id) ON DELETE CASCADE;

--
-- Name: analysis_events fk_analysis_events_match; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_events
    ADD CONSTRAINT fk_analysis_events_match FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE;

--
-- Name: analysis_events fk_analysis_events_player; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_events
    ADD CONSTRAINT fk_analysis_events_player FOREIGN KEY (player_id) REFERENCES public.players(id);

--
-- Name: analysis_events fk_analysis_events_video; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_events
    ADD CONSTRAINT fk_analysis_events_video FOREIGN KEY (video_id) REFERENCES public.match_videos(id) ON DELETE CASCADE;

--
-- Name: article_tags fk_articles_tags; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tags
    ADD CONSTRAINT fk_articles_tags FOREIGN KEY (article_id) REFERENCES public.articles(id);

--
-- Name: club_leagues fk_club_leagues_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_leagues
    ADD CONSTRAINT fk_club_leagues_club FOREIGN KEY (club_id) REFERENCES public.clubs(id);

--
-- Name: club_leagues fk_club_leagues_league; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.club_leagues
    ADD CONSTRAINT fk_club_leagues_league FOREIGN KEY (league_id) REFERENCES public.leagues(id);

--
-- Name: players fk_clubs_players; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT fk_clubs_players FOREIGN KEY (club_id) REFERENCES public.clubs(id);

--
-- Name: lineup_players fk_formations_lineup; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lineup_players
    ADD CONSTRAINT fk_formations_lineup FOREIGN KEY (formation_id) REFERENCES public.formations(id) ON DELETE CASCADE;

--
-- Name: substitutes fk_formations_substitutes; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.substitutes
    ADD CONSTRAINT fk_formations_substitutes FOREIGN KEY (formation_id) REFERENCES public.formations(id) ON DELETE CASCADE;

--
-- Name: unavailable_players fk_formations_unavailable; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unavailable_players
    ADD CONSTRAINT fk_formations_unavailable FOREIGN KEY (formation_id) REFERENCES public.formations(id) ON DELETE CASCADE;

--
-- Name: users fk_leagues_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_leagues_users FOREIGN KEY (league_id) REFERENCES public.leagues(id);

--
-- Name: match_analysts fk_match_analysts_match; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_analysts
    ADD CONSTRAINT fk_match_analysts_match FOREIGN KEY (match_id) REFERENCES public.matches(id);

--
-- Name: match_analysts fk_match_analysts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_analysts
    ADD CONSTRAINT fk_match_analysts_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: match_videos fk_match_videos_match; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_videos
    ADD CONSTRAINT fk_match_videos_match FOREIGN KEY (match_id) REFERENCES public.matches(id);

--
-- Name: matches fk_matches_away_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fk_matches_away_club FOREIGN KEY (away_club_id) REFERENCES public.clubs(id);

--
-- Name: match_events fk_matches_events; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_events
    ADD CONSTRAINT fk_matches_events FOREIGN KEY (match_id) REFERENCES public.matches(id);

--
-- Name: formations fk_matches_formations; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formations
    ADD CONSTRAINT fk_matches_formations FOREIGN KEY (match_id) REFERENCES public.matches(id);

--
-- Name: matches fk_matches_home_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fk_matches_home_club FOREIGN KEY (home_club_id) REFERENCES public.clubs(id);

--
-- Name: matches fk_matches_league; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fk_matches_league FOREIGN KEY (league_id) REFERENCES public.leagues(id);

--
-- Name: player_stats fk_players_stats; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_stats
    ADD CONSTRAINT fk_players_stats FOREIGN KEY (player_id) REFERENCES public.players(id);

--
-- Name: users fk_users_club; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_club FOREIGN KEY (club_id) REFERENCES public.clubs(id);

--
--

